num_classes: 10
delta: 32
num_workers: 2
save_path: './checkpoints/full_unbalanced'
load_checkpoint: './trained_models/full_unbalanced.pt'
ids_folder: '../data/full_unbalanced'
csv_dir: '../data/full_unbalanced'
zipped: 1
notes_zip_or_dir: '../data/full_unbalanced/notes.zip'
cuda: 0
