num_classes: 10
delta: 32
num_workers: 2
save_path: './checkpoints'
load_checkpoint: './checkpoints/epoch_1.pt'
ids_folder: './checkpoints/final_ids_small_unbalanced'
csv_dir: '../selected_unbalanced'
zipped: 1
notes_zip_or_dir: '../selected_unbalanced/notes.zip'
cuda: 0
