num_epochs: 100
learning_rate: 0.0001

num_classes: 10
delta: 32
starting_epoch: 1
batch_size: 1
num_workers: 2
save_path: './checkpoints/small_unbalanced'
load_checkpoint: ''
ids_folder: '../data/small_unbalanced'
csv_dir: '../data/small_unbalanced'
zipped: 1
notes_zip_or_dir: '../data/small_unbalanced/notes.zip'
partial_dataset: -1
cuda: 0
random_seed: 1
