num_epochs: 100
learning_rate: 0.0001

num_classes: 10
delta: 32
starting_epoch: 1
batch_size: 1
num_workers: 2
save_path: './checkpoints/max_balanced'
load_checkpoint: ''
ids_folder: '../data/max_balanced'
csv_dir: '../data/max_balanced'
zipped: 1
notes_zip_or_dir: '../data/max_balanced/notes.zip'
partial_dataset: -1
cuda: 0
random_seed: 1
