num_classes: 10
delta: 32
num_workers: 2
save_path: './checkpoints/small_balanced'
load_checkpoint: './trained_models/small_balanced.pt'
ids_folder: '../data/small_balanced'
csv_dir: '../data/small_balanced'
zipped: 1
notes_zip_or_dir: '../data/small_balanced/notes.zip'
cuda: 0
